#!/bin/bash

SCRIPT_PATH=/home/techmi5/public_html/gospelpedia/simplyhired-feed
SCRIPT=cv-simplyhired-cli.php
DELETE_SCRIPT=cv-simplyhired-delete.php

# First, delete what is currently stored.
php $SCRIPT_PATH/$DELETE_SCRIPT

# Request for all the cities in the US at 100-mile radius
# (the Metropolitan Statistical Area list in techmi5_voleng.ZIPMSAs)
# See distribution at http://batchgeo.com/map/54273c4bd89db98c8cf92b00305e1c14

php $SCRIPT_PATH/$SCRIPT 76443                       # Abilene (Abilene, TX)
php $SCRIPT_PATH/$SCRIPT 00690                       # Aguadilla-Isabela-San Sebastian (Aguadilla, PR)
php $SCRIPT_PATH/$SCRIPT 99545                       # AK NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 44056                       # Akron (Akron, OH)
php $SCRIPT_PATH/$SCRIPT 35010                       # AL NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 31701                       # Albany (Albany, GA)
php $SCRIPT_PATH/$SCRIPT 12007                       # Albany-Schenectady-Troy (Albany, NY)
php $SCRIPT_PATH/$SCRIPT 87001                       # Albuquerque (Albuquerque, NM)
php $SCRIPT_PATH/$SCRIPT 71301                       # Alexandria (Alexandria, LA)
php $SCRIPT_PATH/$SCRIPT 96799                       # All other territories and foreign countries ()
php $SCRIPT_PATH/$SCRIPT 08886                       # Allentown-Bethlehem-Easton (Allentown, PA)
php $SCRIPT_PATH/$SCRIPT 16601                       # Altoona (Altoona, PA)
php $SCRIPT_PATH/$SCRIPT 79012                       # Amarillo (Amarillo, TX)
php $SCRIPT_PATH/$SCRIPT 50010                       # Ames (Ames, IA)
php $SCRIPT_PATH/$SCRIPT 99501                       # Anchorage (Anchorage, AK)
php $SCRIPT_PATH/$SCRIPT 29621                       # Anderson (Anderson, SC)
php $SCRIPT_PATH/$SCRIPT 48103                       # Ann Arbor (Ann Arbor, MI)
php $SCRIPT_PATH/$SCRIPT 36201                       # Anniston-Oxford (Anniston, AL)
php $SCRIPT_PATH/$SCRIPT 53014                       # Appleton (Appleton, WI)
php $SCRIPT_PATH/$SCRIPT 71630                       # AR NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 09524                       # ARMED FORCES ()
php $SCRIPT_PATH/$SCRIPT 28701                       # Asheville (Asheville, NC)
php $SCRIPT_PATH/$SCRIPT 30601                       # Athens-Clark County (Athens, GA)
php $SCRIPT_PATH/$SCRIPT 30002                       # Atlanta-Sandy Springs-Marietta (Atlanta, GA)
php $SCRIPT_PATH/$SCRIPT 08406                       # Atlantic City (Atlantic City, NJ)
php $SCRIPT_PATH/$SCRIPT 36801                       # Auburn-Opelika (Auburn, AL)
php $SCRIPT_PATH/$SCRIPT 29137                       # Augusta-Richmond County (Augusta, GA)
php $SCRIPT_PATH/$SCRIPT 73301                       # Austin-Round Rock (Austin, TX)
php $SCRIPT_PATH/$SCRIPT 85235                       # AZ NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 93203                       # Bakersfield (Bakersfield, CA)
php $SCRIPT_PATH/$SCRIPT 20701                       # Baltimore-Towson (Baltimore, MD)
php $SCRIPT_PATH/$SCRIPT 04969                       # Bangor (Bangor, ME)
php $SCRIPT_PATH/$SCRIPT 02675                       # Barnstable Town (Barnstable, MA)
php $SCRIPT_PATH/$SCRIPT 70346                       # Baton Rouge (Baton Rouge, LA)
php $SCRIPT_PATH/$SCRIPT 49011                       # Battle Creek (Battle Creek, MI)
php $SCRIPT_PATH/$SCRIPT 48611                       # Bay City (Bay City, MI)
php $SCRIPT_PATH/$SCRIPT 77374                       # Beaumont-Port Arthur (Beaumont, TX)
php $SCRIPT_PATH/$SCRIPT 98220                       # Bellingham (Bellingham, WA)
php $SCRIPT_PATH/$SCRIPT 97701                       # Bend (Bend, OR)
php $SCRIPT_PATH/$SCRIPT 59002                       # Billings (Billings, MT)
php $SCRIPT_PATH/$SCRIPT 13732                       # Binghamton (Binghamton, NY)
php $SCRIPT_PATH/$SCRIPT 35004                       # Birmingham-Hoover (Birmingham, AL)
php $SCRIPT_PATH/$SCRIPT 58477                       # Bismarck (Bismarck, ND)
php $SCRIPT_PATH/$SCRIPT 23825                       # Blacksburg-Christiansburg-Radford (Blacksburg, VA)
php $SCRIPT_PATH/$SCRIPT 47401                       # Bloomington (Bloomington, IN)
php $SCRIPT_PATH/$SCRIPT 61701                       # Bloomington-Normal (Bloomington, IL)
php $SCRIPT_PATH/$SCRIPT 83602                       # Boise City-Nampa (Boise City, ID)
php $SCRIPT_PATH/$SCRIPT 05544                       # Boston-Cambridge-Quincy (Boston, MA)
php $SCRIPT_PATH/$SCRIPT 80025                       # Boulder (Boulder, CO)
php $SCRIPT_PATH/$SCRIPT 42101                       # Bowling Green (Bowling Green, KY)
php $SCRIPT_PATH/$SCRIPT 98061                       # Bremerton-Silverdale (Bremerton, WA)
php $SCRIPT_PATH/$SCRIPT 06928                       # Bridgeport-Stamford-Norwalk (Bridgeport, CT)
php $SCRIPT_PATH/$SCRIPT 78520                       # Brownsville-Harlingen (Brownsville, TX)
php $SCRIPT_PATH/$SCRIPT 31304                       # Brunswick (Brunswick, GA)
php $SCRIPT_PATH/$SCRIPT 14001                       # Buffalo-Niagara Falls (Buffalo, NY)
php $SCRIPT_PATH/$SCRIPT 27201                       # Burlington (Burlington, NC)
php $SCRIPT_PATH/$SCRIPT 05495                       # Burlington-South Burlington (Burlington, VT)
php $SCRIPT_PATH/$SCRIPT 92328                       # CA NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 44601                       # Canton-Massillon (Canton, OH)
php $SCRIPT_PATH/$SCRIPT 33900                       # Cape Coral-Fort Myers (Cape Coral, FL)
php $SCRIPT_PATH/$SCRIPT 89701                       # Carson City (Carson City, NV)
php $SCRIPT_PATH/$SCRIPT 82601                       # Casper (Casper, WY)
php $SCRIPT_PATH/$SCRIPT 52202                       # Cedar Rapids (Cedar Rapids, IA)
php $SCRIPT_PATH/$SCRIPT 60919                       # Champaign-Urbana (Champaign, IL)
php $SCRIPT_PATH/$SCRIPT 25003                       # Charleston (Charleston, WV)
php $SCRIPT_PATH/$SCRIPT 29401                       # Charleston-North Charleston (Charleston, SC)
php $SCRIPT_PATH/$SCRIPT 28006                       # Charlotte-Gastonia-Concord (Charlotte, NC)
php $SCRIPT_PATH/$SCRIPT 22901                       # Charlottesville (Charlottesville, VA)
php $SCRIPT_PATH/$SCRIPT 30707                       # Chattanooga (Chattanooga, TN)
php $SCRIPT_PATH/$SCRIPT 82001                       # Cheyenne (Cheyenne, WY)
php $SCRIPT_PATH/$SCRIPT 46301                       # Chicago-Naperville-Joliet (Chicago, IL)
php $SCRIPT_PATH/$SCRIPT 95914                       # Chico (Chico, CA)
php $SCRIPT_PATH/$SCRIPT 41001                       # Cincinnati-Middletown (Cincinnati, OH)
php $SCRIPT_PATH/$SCRIPT 37023                       # Clarksville (Clarksville, TN)
php $SCRIPT_PATH/$SCRIPT 37307                       # Cleveland (Cleveland, TN)
php $SCRIPT_PATH/$SCRIPT 44001                       # Cleveland-Elyria-Mentor (Cleveland, OH)
php $SCRIPT_PATH/$SCRIPT 80423                       # CO NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 83801                       # Coeur d'Alene (Coeur d'Alene, ID)
php $SCRIPT_PATH/$SCRIPT 76629                       # College Station-Bryan (College Station, TX)
php $SCRIPT_PATH/$SCRIPT 80132                       # Colorado Springs (Colorado Springs, CO)
php $SCRIPT_PATH/$SCRIPT 29002                       # Columbia (Columbia, SC)
php $SCRIPT_PATH/$SCRIPT 31803                       # Columbus (Columbus, OH)
php $SCRIPT_PATH/$SCRIPT 78330                       # Corpus Christi (Corpus Christi, TX)
php $SCRIPT_PATH/$SCRIPT 97324                       # Corvalis (Corvalis, OR)
php $SCRIPT_PATH/$SCRIPT 06798                       # CT NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 21501                       # Cumberland (Cumberland, MD)
php $SCRIPT_PATH/$SCRIPT 75001                       # Dallas-Fort Worth-Arlington (Dallas, TX)
php $SCRIPT_PATH/$SCRIPT 30705                       # Dalton (Dalton, GA)
php $SCRIPT_PATH/$SCRIPT 24069                       # Danville (Danville, VA)
php $SCRIPT_PATH/$SCRIPT 52722                       # Davenport-Moline-Rock Island (Davenport, IA)
php $SCRIPT_PATH/$SCRIPT 45070                       # Dayton (Dayton, OH)
php $SCRIPT_PATH/$SCRIPT 19930                       # DE NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 35601                       # Decatur (Decatur, AL)
php $SCRIPT_PATH/$SCRIPT 32105                       # Deltona-Daytona Beach-Ormond Beach (Deltona, FL)
php $SCRIPT_PATH/$SCRIPT 80001                       # Denver-Aurora (Denver, CO)
php $SCRIPT_PATH/$SCRIPT 50001                       # Des Moines-West Des Moines (Des Moines, IA)
php $SCRIPT_PATH/$SCRIPT 48001                       # Detroit-Warren-Livonia (Detroit, MI)
php $SCRIPT_PATH/$SCRIPT 36301                       # Dothan (Dothan, AL)
php $SCRIPT_PATH/$SCRIPT 19901                       # Dover (Dover, DE)
php $SCRIPT_PATH/$SCRIPT 52001                       # Dubuque (Dubuque, IA)
php $SCRIPT_PATH/$SCRIPT 54820                       # Duluth (Duluth, MN)
php $SCRIPT_PATH/$SCRIPT 27207                       # Durham (Durham, NC)
php $SCRIPT_PATH/$SCRIPT 54701                       # Eau Claire (Eau Claire, WI)
php $SCRIPT_PATH/$SCRIPT 92222                       # El Centro (El Centro, CA)
php $SCRIPT_PATH/$SCRIPT 79821                       # El Paso (El Paso, TX)
php $SCRIPT_PATH/$SCRIPT 40121                       # Elizabethtown (Elizabethtown, KY)
php $SCRIPT_PATH/$SCRIPT 46507                       # Elkhart-Goshen (Elkhart, IN)
php $SCRIPT_PATH/$SCRIPT 14814                       # Elmira (Elmira, NY)
php $SCRIPT_PATH/$SCRIPT 16401                       # Erie (Erie, PA)
php $SCRIPT_PATH/$SCRIPT 97401                       # Eugene-Springfield (Eugene, OR)
php $SCRIPT_PATH/$SCRIPT 42402                       # Evansville (Evansville, IN)
php $SCRIPT_PATH/$SCRIPT 99701                       # Fairbanks (Fairbanks, AK)
php $SCRIPT_PATH/$SCRIPT 00773                       # Fajardo (Fajardo, PR)
php $SCRIPT_PATH/$SCRIPT 56513                       # Fargo (Fargo, ND)
php $SCRIPT_PATH/$SCRIPT 87037                       # Farmington (Farmington, NM)
php $SCRIPT_PATH/$SCRIPT 28301                       # Fayetteville (Fayetteville, NC)
php $SCRIPT_PATH/$SCRIPT 64831                       # Fayetteville-Springdale-Rogers (Fayetteville, AR)
php $SCRIPT_PATH/$SCRIPT 32007                       # FL NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 85931                       # Flagstaff (Flagstaff, AZ)
php $SCRIPT_PATH/$SCRIPT 48411                       # Flint (Flint, MI)
php $SCRIPT_PATH/$SCRIPT 29069                       # Florence (Florence, SC)
php $SCRIPT_PATH/$SCRIPT 35610                       # Florence-Muscle Shoals (Florence, AL)
php $SCRIPT_PATH/$SCRIPT 53010                       # Fond du Lac (Fond du Lac, WI)
php $SCRIPT_PATH/$SCRIPT 80511                       # Fort Collins-Loveland (Fort Collins, CO)
php $SCRIPT_PATH/$SCRIPT 72820                       # Fort Smith (Fort Smith, AR)
php $SCRIPT_PATH/$SCRIPT 32531                       # Fort Walton Beach-Crestview-Destin (Fort Walton Beach, FL)
php $SCRIPT_PATH/$SCRIPT 46704                       # Fort Wayne (Fort Wayne, IN)
php $SCRIPT_PATH/$SCRIPT 93210                       # Fresno (Fresno, CA)
php $SCRIPT_PATH/$SCRIPT 30104                       # GA NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 35901                       # Gadsden (Gadsden, AL)
php $SCRIPT_PATH/$SCRIPT 30501                       # Gainesville (Gainesville, GA)
php $SCRIPT_PATH/$SCRIPT 12057                       # Glens Falls (Glens Falls, NY)
php $SCRIPT_PATH/$SCRIPT 27530                       # Goldsboro (Goldsboro, NC)
php $SCRIPT_PATH/$SCRIPT 56517                       # Grand Forks (Grand Forks, ND)
php $SCRIPT_PATH/$SCRIPT 81501                       # Grand Junction (Grand Junction, CO)
php $SCRIPT_PATH/$SCRIPT 48809                       # Grand Rapids-Wyoming (Grand Rapids, MI)
php $SCRIPT_PATH/$SCRIPT 59401                       # Great Falls (Great Falls, MT)
php $SCRIPT_PATH/$SCRIPT 80504                       # Greeley (Greeley, CO)
php $SCRIPT_PATH/$SCRIPT 54101                       # Green Bay (Green Bay, WI)
php $SCRIPT_PATH/$SCRIPT 27025                       # Greensboro-High Point (Greensboro, NC)
php $SCRIPT_PATH/$SCRIPT 27811                       # Greenville (Greenville, NC)
php $SCRIPT_PATH/$SCRIPT 29325                       # Greenville-Mauldin-Easley (Greenville, SC)
php $SCRIPT_PATH/$SCRIPT 96910                       # GU NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 00784                       # Guayama (Guayama, PR)
php $SCRIPT_PATH/$SCRIPT 39501                       # Gulfport-Biloxi (Gulfport, MS)
php $SCRIPT_PATH/$SCRIPT 21711                       # Hagerstown-Martinsburg (Hagerstown, MD)
php $SCRIPT_PATH/$SCRIPT 93202                       # Hanford-Corcoran (Hanford, CA)
php $SCRIPT_PATH/$SCRIPT 17001                       # Harrisburg-Carlisle (Harrisburg, PA)
php $SCRIPT_PATH/$SCRIPT 22801                       # Harrisonburg (Harrisonburg, VA)
php $SCRIPT_PATH/$SCRIPT 06498                       # Hartford-West Hartford-East Hartford (Hartford, CT)
php $SCRIPT_PATH/$SCRIPT 39401                       # Hattiesburg (Hattiesburg, MS)
php $SCRIPT_PATH/$SCRIPT 96703                       # HI NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 28601                       # Hickory-Lenoir-Morganton (Hickory, NC)
php $SCRIPT_PATH/$SCRIPT 31301                       # Hinesville-Fort Stewart (Hinesville, GA)
php $SCRIPT_PATH/$SCRIPT 49401                       # Holland-Grand Haven (Holland, MI)
php $SCRIPT_PATH/$SCRIPT 96701                       # Honolulu (Honolulu, HI)
php $SCRIPT_PATH/$SCRIPT 71901                       # Hot Springs (Hot Springs, AR)
php $SCRIPT_PATH/$SCRIPT 70301                       # Houma-Bayou Cane-Thibodaux (Houma, LA)
php $SCRIPT_PATH/$SCRIPT 77001                       # Houston-Sugar Land-Baytown (Houston, TX)
php $SCRIPT_PATH/$SCRIPT 25504                       # Huntington-Ashland (Huntington, WV)
php $SCRIPT_PATH/$SCRIPT 35611                       # Huntsville (Huntsville, AL)
php $SCRIPT_PATH/$SCRIPT 50002                       # IA NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 83203                       # ID NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 83401                       # Idaho Falls (Idaho Falls, ID)
php $SCRIPT_PATH/$SCRIPT 60113                       # IL NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 46035                       # IN NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 46030                       # Indianapolis-Carmel (Indianapolis, IN)
php $SCRIPT_PATH/$SCRIPT 52201                       # Iowa City (Iowa City, IA)
php $SCRIPT_PATH/$SCRIPT 13053                       # Ithaca (Ithaca, NY)
php $SCRIPT_PATH/$SCRIPT 38301                       # Jackson (Jackson, TN)
php $SCRIPT_PATH/$SCRIPT 28445                       # Jacksonville (Jacksonville, NC)
php $SCRIPT_PATH/$SCRIPT 53501                       # Janesville (Janesville, WI)
php $SCRIPT_PATH/$SCRIPT 63388                       # Jefferson City (Jefferson City, MO)
php $SCRIPT_PATH/$SCRIPT 37601                       # Johnson City (Johnson City, TN)
php $SCRIPT_PATH/$SCRIPT 15714                       # Johnstown (Johnstown, PA)
php $SCRIPT_PATH/$SCRIPT 72354                       # Jonesboro (Jonesboro, AR)
php $SCRIPT_PATH/$SCRIPT 64755                       # Joplin (Joplin, MO)
php $SCRIPT_PATH/$SCRIPT 49001                       # Kalamazoo-Portage (Kalamazoo, MI)
php $SCRIPT_PATH/$SCRIPT 60901                       # Kankakee-Bradley (Kankakee, IL)
php $SCRIPT_PATH/$SCRIPT 64001                       # Kansas City (Kansas City, MO)
php $SCRIPT_PATH/$SCRIPT 99301                       # Kennewick-Richland-Pasco (Kennewick, WA)
php $SCRIPT_PATH/$SCRIPT 76501                       # Killeen-Temple-Fort Hood (Killeen, TX)
php $SCRIPT_PATH/$SCRIPT 24201                       # Kingsport-Bristol-Bristol (Kingsport, TN)
php $SCRIPT_PATH/$SCRIPT 12401                       # Kingston (Kingston, NY)
php $SCRIPT_PATH/$SCRIPT 37701                       # Knoxville (Knoxville, TN)
php $SCRIPT_PATH/$SCRIPT 46045                       # Kokomo (Kokomo, IN)
php $SCRIPT_PATH/$SCRIPT 66002                       # KS NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 40009                       # KY NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 54601                       # La Crosse (La Crosse, WI)
php $SCRIPT_PATH/$SCRIPT 70052                       # LA NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 46913                       # Lafayette (Lafayette, LA)
php $SCRIPT_PATH/$SCRIPT 70601                       # Lake Charles (Lake Charles, LA)
php $SCRIPT_PATH/$SCRIPT 85360                       # Lake Havasu City-Kingman (Lake Havasu City, AZ)
php $SCRIPT_PATH/$SCRIPT 33801                       # Lakeland (Lakeland, FL)
php $SCRIPT_PATH/$SCRIPT 17022                       # Lancaster (Lancaster, PA)
php $SCRIPT_PATH/$SCRIPT 48805                       # Lansing-East Lansing (Lansing, MI)
php $SCRIPT_PATH/$SCRIPT 78040                       # Laredo (Laredo, TX)
php $SCRIPT_PATH/$SCRIPT 87936                       # Las Cruces (Las Cruces, NM)
php $SCRIPT_PATH/$SCRIPT 88901                       # Las Vegas-Paradise (Las Vegas, NV)
php $SCRIPT_PATH/$SCRIPT 66006                       # Lawrence (Lawrence, KS)
php $SCRIPT_PATH/$SCRIPT 73501                       # Lawton (Lawton, OK)
php $SCRIPT_PATH/$SCRIPT 17003                       # Lebanon (Lebanon, PA)
php $SCRIPT_PATH/$SCRIPT 83501                       # Lewiston (Lewiston, ID)
php $SCRIPT_PATH/$SCRIPT 04291                       # Lewiston-Auburn (Lewiston, ME)
php $SCRIPT_PATH/$SCRIPT 40320                       # Lexington-Fayette (Lexington, KY)
php $SCRIPT_PATH/$SCRIPT 45801                       # Lima (Lima, OH)
php $SCRIPT_PATH/$SCRIPT 68313                       # Lincoln (Lincoln, NE)
php $SCRIPT_PATH/$SCRIPT 72001                       # Little Rock-North Little Rock-Conway (Little Rock, AR)
php $SCRIPT_PATH/$SCRIPT 83228                       # Logan (Logan, UT)
php $SCRIPT_PATH/$SCRIPT 75601                       # Longview (Longview, WA)
php $SCRIPT_PATH/$SCRIPT 90001                       # Los Angeles-Long Beach-Santa Ana (Los Angeles, CA)
php $SCRIPT_PATH/$SCRIPT 40003                       # Louisville/Jefferson County (Louisville, KY)
php $SCRIPT_PATH/$SCRIPT 79322                       # Lubbock (Lubbock, TX)
php $SCRIPT_PATH/$SCRIPT 23939                       # Lynchburg (Lynchburg, VA)
php $SCRIPT_PATH/$SCRIPT 02713                       # MA NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 31004                       # Macon (Macon, GA)
php $SCRIPT_PATH/$SCRIPT 93601                       # Madera (Madera, CA)
php $SCRIPT_PATH/$SCRIPT 53503                       # Madison (Madison, WI)
php $SCRIPT_PATH/$SCRIPT 03468                       # Manchester-Nashua (Manchester, NH)
php $SCRIPT_PATH/$SCRIPT 44813                       # Mansfield (Mansfield, OH)
php $SCRIPT_PATH/$SCRIPT 00682                       # Mayaguez (Mayaguez, PR)
php $SCRIPT_PATH/$SCRIPT 78501                       # McAllen-Edinburg-Mission (McAllen, TX)
php $SCRIPT_PATH/$SCRIPT 20606                       # MD NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 04992                       # ME NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 97501                       # Medford (Medford, OR)
php $SCRIPT_PATH/$SCRIPT 37501                       # Memphis (Memphis, TN)
php $SCRIPT_PATH/$SCRIPT 93620                       # Merced (Merced, CA)
php $SCRIPT_PATH/$SCRIPT 48401                       # MI NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 33002                       # Miami-Fort Lauderdale-Pompano Beach (Miami, FL)
php $SCRIPT_PATH/$SCRIPT 46340                       # Michigan City-La Porte (Michigan City, IN)
php $SCRIPT_PATH/$SCRIPT 79701                       # Midland (Midland, TX)
php $SCRIPT_PATH/$SCRIPT 53002                       # Milwaukee-Waukesha-West Allis (Milwaukee, WI)
php $SCRIPT_PATH/$SCRIPT 54002                       # Minneapolis-St. Paul-Bloomington (Minneapolis-St. Paul, MN)
php $SCRIPT_PATH/$SCRIPT 59801                       # Missoula (Missoula, MT)
php $SCRIPT_PATH/$SCRIPT 55007                       # MN NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 63036                       # MO NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 36505                       # Mobile (Mobile, AL)
php $SCRIPT_PATH/$SCRIPT 95307                       # Modesto (Modesto, CA)
php $SCRIPT_PATH/$SCRIPT 48110                       # Monroe (Monroe, MI)
php $SCRIPT_PATH/$SCRIPT 36003                       # Montgomery (Montgomery, AL)
php $SCRIPT_PATH/$SCRIPT 26374                       # Morgantown (Morgantown, WV)
php $SCRIPT_PATH/$SCRIPT 37708                       # Morristown (Morristown, TN)
php $SCRIPT_PATH/$SCRIPT 98221                       # Mount Vernon-Anacortes (Mount Vernon, WA)
php $SCRIPT_PATH/$SCRIPT 38601                       # MS NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 59001                       # MT NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 47302                       # Muncie (Muncie, IN)
php $SCRIPT_PATH/$SCRIPT 49303                       # Muskegon-Norton Shores (Muskegon, MI)
php $SCRIPT_PATH/$SCRIPT 29511                       # Myrtle Beach-Conway-North Myrtle Beach (Myrtle Beach, SC)
php $SCRIPT_PATH/$SCRIPT 94503                       # Napa (Napa, CA)
php $SCRIPT_PATH/$SCRIPT 34101                       # Naples-Marco Island (Naples, FL)
php $SCRIPT_PATH/$SCRIPT 37010                       # Nashville-Davidson-Murfreesboro-Franklin (Nashville, TN)
php $SCRIPT_PATH/$SCRIPT 27007                       # NC NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 58001                       # ND NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 68001                       # NE NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 06770                       # New Haven-Milford (New Haven, CT)
php $SCRIPT_PATH/$SCRIPT 70001                       # New Orleans-Metairie-Kenner (New Orleans, LA)
php $SCRIPT_PATH/$SCRIPT 08989                       # New York-Northern New Jersey-Long Island (New York, NY)
php $SCRIPT_PATH/$SCRIPT 03897                       # NH NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 49022                       # Niles-Benton Harbor (Niles, MI)
php $SCRIPT_PATH/$SCRIPT 87005                       # NM NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 06474                       # Norwich-New London (Norwich, CT)
php $SCRIPT_PATH/$SCRIPT 89001                       # NV NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 12010                       # NY NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 32111                       # Ocala (Ocala, FL)
php $SCRIPT_PATH/$SCRIPT 08270                       # Ocean City (Ocean City, NJ)
php $SCRIPT_PATH/$SCRIPT 79741                       # Odessa (Odessa, TX)
php $SCRIPT_PATH/$SCRIPT 84010                       # Ogden-Clearfield (Ogden, UT)
php $SCRIPT_PATH/$SCRIPT 43005                       # OH NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 73001                       # OK NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 73002                       # Oklahoma City (Oklahoma City, OK)
php $SCRIPT_PATH/$SCRIPT 98501                       # Olympia (Olympia, WA)
php $SCRIPT_PATH/$SCRIPT 51501                       # Omaha-Council Bluffs (Omaha, NE)
php $SCRIPT_PATH/$SCRIPT 97001                       # OR NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 32102                       # Orlando-Kissimmee (Orlando, FL)
php $SCRIPT_PATH/$SCRIPT 54901                       # Oshkosh-Neenah (Oshkosh, WI)
php $SCRIPT_PATH/$SCRIPT 42301                       # Owensboro (Owensboro, KY)
php $SCRIPT_PATH/$SCRIPT 91319                       # Oxnard-Thousand Oaks-Ventura (Oxnard, CA)
php $SCRIPT_PATH/$SCRIPT 15310                       # PA NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 32754                       # Palm Bay-Melbourne-Titusville (Palm Bay, FL)
php $SCRIPT_PATH/$SCRIPT 32110                       # Palm Coast (Palm Coast, FL)
php $SCRIPT_PATH/$SCRIPT 32401                       # Panama City-Lynn Haven (Panama City, FL)
php $SCRIPT_PATH/$SCRIPT 26101                       # Parkersburg-Marietta-Vienna (Parkersburg, WV)
php $SCRIPT_PATH/$SCRIPT 39452                       # Pascagoula (Pascagoula, MS)
php $SCRIPT_PATH/$SCRIPT 32501                       # Pensacola-Ferry Pass-Brent (Pensacola, FL)
php $SCRIPT_PATH/$SCRIPT 61369                       # Peoria (Peoria, IL)
php $SCRIPT_PATH/$SCRIPT 08641                       # Philadelphia-Camden-Wilmington (Philadelphia, PA)
php $SCRIPT_PATH/$SCRIPT 85001                       # Phoenix-Mesa-Scottsdale (Phoenix, AZ)
php $SCRIPT_PATH/$SCRIPT 71601                       # Pine Bluff (Pine Bluff, AR)
php $SCRIPT_PATH/$SCRIPT 15001                       # Pittsburgh (Pittsburgh, PA)
php $SCRIPT_PATH/$SCRIPT 01343                       # Pittsfield (Pittsfield, MA)
php $SCRIPT_PATH/$SCRIPT 83201                       # Pocatello (Pocatello, ID)
php $SCRIPT_PATH/$SCRIPT 00795                       # Ponce (Ponce, PR)
php $SCRIPT_PATH/$SCRIPT 33455                       # Port St. Lucie (Port St. Lucie, FL)
php $SCRIPT_PATH/$SCRIPT 04579                       # Portland-South Portland-Biddeford (Portland, ME)
php $SCRIPT_PATH/$SCRIPT 97004                       # Portland-Vancouver-Beaverton (Portland, OR)
php $SCRIPT_PATH/$SCRIPT 10910                       # Poughkeepsie-Newburgh-Middletown (Poughkeepsie, NY)
php $SCRIPT_PATH/$SCRIPT 00775                       # PR NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 85324                       # Prescott (Prescott, AZ)
php $SCRIPT_PATH/$SCRIPT 02940                       # Providence-New Bedford-Fall River (Providence, RI)
php $SCRIPT_PATH/$SCRIPT 84003                       # Provo-Orem (Provo, UT)
php $SCRIPT_PATH/$SCRIPT 81001                       # Pueblo (Pueblo, CO)
php $SCRIPT_PATH/$SCRIPT 33927                       # Punta Gorda (Punta Gorda, FL)
php $SCRIPT_PATH/$SCRIPT 53105                       # Racine (Racine, WI)
php $SCRIPT_PATH/$SCRIPT 27502                       # Raleigh-Cary (Raleigh, NC)
php $SCRIPT_PATH/$SCRIPT 57626                       # Rapid City (Rapid City, SD)
php $SCRIPT_PATH/$SCRIPT 18056                       # Reading (Reading, PA)
php $SCRIPT_PATH/$SCRIPT 96001                       # Redding (Redding, CA)
php $SCRIPT_PATH/$SCRIPT 89402                       # Reno-Sparks (Reno, NV)
php $SCRIPT_PATH/$SCRIPT 22427                       # Richmond (Richmond, VA)
php $SCRIPT_PATH/$SCRIPT 91701                       # Riverside-San Bernardino-Ontario (Riverside, CA)
php $SCRIPT_PATH/$SCRIPT 24001                       # Roanoke (Roanoke, VA)
php $SCRIPT_PATH/$SCRIPT 13143                       # Rochester (Rochester, NY)
php $SCRIPT_PATH/$SCRIPT 61008                       # Rockford (Rockford, IL)
php $SCRIPT_PATH/$SCRIPT 27801                       # Rocky Mount (Rocky Mount, NC)
php $SCRIPT_PATH/$SCRIPT 30105                       # Rome (Rome, GA)
php $SCRIPT_PATH/$SCRIPT 94203                       # Sacramento-Arden-Arcade-Roseville (Sacramento, CA)
php $SCRIPT_PATH/$SCRIPT 48415                       # Saginaw-Saginaw Township North (Saginaw, MI)
php $SCRIPT_PATH/$SCRIPT 97002                       # Salem (Salem, OR)
php $SCRIPT_PATH/$SCRIPT 93426                       # Salinas (Salinas, CA)
php $SCRIPT_PATH/$SCRIPT 21801                       # Salisbury (Salisbury, MD)
php $SCRIPT_PATH/$SCRIPT 84006                       # Salt Lake City (Salt Lake City, UT)
php $SCRIPT_PATH/$SCRIPT 76886                       # San Angelo (San Angelo, TX)
php $SCRIPT_PATH/$SCRIPT 78002                       # San Antonio (San Antonio, TX)
php $SCRIPT_PATH/$SCRIPT 91901                       # San Diego-Carlsbad-San Marcos (San Diego, CA)
php $SCRIPT_PATH/$SCRIPT 94002                       # San Francisco-Oakland-Fremont (San Francisco, CA)
php $SCRIPT_PATH/$SCRIPT 00683                       # San German-Cabo Rojo (San German, PR)
php $SCRIPT_PATH/$SCRIPT 94022                       # San Jose-Sunnyvale-Santa Clara (San Jose, CA)
php $SCRIPT_PATH/$SCRIPT 00988                       # San Juan-Caguas-Guaynabo (San Juan, PR)
php $SCRIPT_PATH/$SCRIPT 93401                       # San Luis Obispo-Paso Robles (San Luis Obispo, CA)
php $SCRIPT_PATH/$SCRIPT 43438                       # Sandusky (Sandusky, OH)
php $SCRIPT_PATH/$SCRIPT 93013                       # Santa Barbara-Santa Maria-Goleta (Santa Barbara, CA)
php $SCRIPT_PATH/$SCRIPT 95001                       # Santa Cruz-Watsonville (Santa Cruz, CA)
php $SCRIPT_PATH/$SCRIPT 87010                       # Santa Fe (Santa Fe, NM)
php $SCRIPT_PATH/$SCRIPT 94922                       # Santa Rosa-Petaluma (Santa Rosa, CA)
php $SCRIPT_PATH/$SCRIPT 34201                       # Sarasota-Bradenton-Venice (Sarasota, FL)
php $SCRIPT_PATH/$SCRIPT 31302                       # Savannah (Savannah, GA)
php $SCRIPT_PATH/$SCRIPT 29001                       # SC NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 18201                       # Scranton--Wilkes-Barre (Scranton, PA)
php $SCRIPT_PATH/$SCRIPT 57002                       # SD NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 98001                       # Seattle-Tacoma-Bellevue (Seattle, WA)
php $SCRIPT_PATH/$SCRIPT 32948                       # Sebastian-Vero Beach (Sebastian, FL)
php $SCRIPT_PATH/$SCRIPT 53001                       # Sheboygan (Sheboygan, WI)
php $SCRIPT_PATH/$SCRIPT 75020                       # Sherman-Denison (Sherman, TX)
php $SCRIPT_PATH/$SCRIPT 71004                       # Shreveport-Bossier City (Shreveport, LA)
php $SCRIPT_PATH/$SCRIPT 51004                       # Sioux City (Sioux City, IA)
php $SCRIPT_PATH/$SCRIPT 57003                       # Sioux Falls (Sioux Falls, SD)
php $SCRIPT_PATH/$SCRIPT 46530                       # South Bend-Mishawaka (South Bend, IN)
php $SCRIPT_PATH/$SCRIPT 29301                       # Spartanburg (Spartanburg, SC)
php $SCRIPT_PATH/$SCRIPT 99001                       # Spokane (Spokane, WA)
php $SCRIPT_PATH/$SCRIPT 01521                       # Springfield (Springfield, MA)
php $SCRIPT_PATH/$SCRIPT 55353                       # St. Cloud (St. Cloud, MN)
php $SCRIPT_PATH/$SCRIPT 84722                       # St. George (St. George, UT)
php $SCRIPT_PATH/$SCRIPT 64401                       # St. Joseph (St. Joseph, MO)
php $SCRIPT_PATH/$SCRIPT 62001                       # St. Louis (St. Louis, MO)
php $SCRIPT_PATH/$SCRIPT 16677                       # State College (State College, PA)
php $SCRIPT_PATH/$SCRIPT 95201                       # Stockton (Stockton, CA)
php $SCRIPT_PATH/$SCRIPT 29040                       # Sumter (Sumter, SC)
php $SCRIPT_PATH/$SCRIPT 13020                       # Syracuse (Syracuse, NY)
php $SCRIPT_PATH/$SCRIPT 32301                       # Tallahassee (Tallahassee, FL)
php $SCRIPT_PATH/$SCRIPT 33503                       # Tampa-St. Petersburg-Clearwater (Tampa, FL)
php $SCRIPT_PATH/$SCRIPT 47801                       # Terre Haute (Terre Haute, IN)
php $SCRIPT_PATH/$SCRIPT 71834                       # Texarkana (Texarkana, TX)
php $SCRIPT_PATH/$SCRIPT 37012                       # TN NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 43402                       # Toledo (Toledo, OH)
php $SCRIPT_PATH/$SCRIPT 66054                       # Topeka (Topeka, KS)
php $SCRIPT_PATH/$SCRIPT 08695                       # Trenton-Ewing (Trenton, NJ)
php $SCRIPT_PATH/$SCRIPT 85321                       # Tucson (Tucson, AZ)
php $SCRIPT_PATH/$SCRIPT 74001                       # Tulsa (Tulsa, OK)
php $SCRIPT_PATH/$SCRIPT 35401                       # Tuscaloosa (Tuscaloosa, AL)
php $SCRIPT_PATH/$SCRIPT 75102                       # TX NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 75701                       # Tyler (Tyler, TX)
php $SCRIPT_PATH/$SCRIPT 84001                       # UT NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 13054                       # Utica-Rome (Utica, NY)
php $SCRIPT_PATH/$SCRIPT 20106                       # VA NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 31601                       # Valdosta (Valdosta, GA)
php $SCRIPT_PATH/$SCRIPT 94510                       # Vallejo-Fairfield (Vallejo, CA)
php $SCRIPT_PATH/$SCRIPT 00851                       # VI NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 77901                       # Victoria (Victoria, TX)
php $SCRIPT_PATH/$SCRIPT 08362                       # Vineland-Millville-Bridgeton (Vineland, NJ)
php $SCRIPT_PATH/$SCRIPT 23001                       # Virginia Beach-Norfolk-Newport News (Virginia Beach, VA)
php $SCRIPT_PATH/$SCRIPT 93201                       # Visalia-Porterville (Visalia, CA)
php $SCRIPT_PATH/$SCRIPT 05907                       # VT NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 98222                       # WA NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 76524                       # Waco (Waco, TX)
php $SCRIPT_PATH/$SCRIPT 31005                       # Warner Robins (Warner Robins, GA)
php $SCRIPT_PATH/$SCRIPT 20001                       # Washington-Arlington-Alexandria (Washington, DC)
php $SCRIPT_PATH/$SCRIPT 50609                       # Waterloo-Cedar Falls (Waterloo, IA)
php $SCRIPT_PATH/$SCRIPT 54401                       # Wausau (Wausau, WI)
php $SCRIPT_PATH/$SCRIPT 26030                       # Weirton-Steubenville (Weirton, WV)
php $SCRIPT_PATH/$SCRIPT 98801                       # Wenatchee (Wenatchee, WA)
php $SCRIPT_PATH/$SCRIPT 26003                       # Wheeling (Wheeling, WV)
php $SCRIPT_PATH/$SCRIPT 53003                       # WI NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 66842                       # Wichita (Wichita, KS)
php $SCRIPT_PATH/$SCRIPT 76228                       # Wichita Falls (Wichita Falls, TX)
php $SCRIPT_PATH/$SCRIPT 17701                       # Williamsport (Williamsport, PA)
php $SCRIPT_PATH/$SCRIPT 28401                       # Wilmington (Wilmington, NC)
php $SCRIPT_PATH/$SCRIPT 22601                       # Winchester (Winchester, VA)
php $SCRIPT_PATH/$SCRIPT 27006                       # Winston-Salem (Winston-Salem, NC)
php $SCRIPT_PATH/$SCRIPT 01772                       # Worcester (Worcester, MA)
php $SCRIPT_PATH/$SCRIPT 24701                       # WV NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 82051                       # WY NONMETROPOLITAN AREA ()
php $SCRIPT_PATH/$SCRIPT 98901                       # Yakima (Yakima, WA)
php $SCRIPT_PATH/$SCRIPT 00785                       # Yauco (Yauco, PR)
php $SCRIPT_PATH/$SCRIPT 17019                       # York-Hanover (York, PA)
php $SCRIPT_PATH/$SCRIPT 16113                       # Youngstown-Warren-Boardman (Youngstown, OH)
php $SCRIPT_PATH/$SCRIPT 95659                       # Yuba City (Yuba City, CA)
php $SCRIPT_PATH/$SCRIPT 85333                       # Yuma (Yuma, AZ)

# English-speaking countries

# Canadian provinces (http://en.wikipedia.org/wiki/Provinces_and_territories_of_Canada)

php $SCRIPT_PATH/$SCRIPT AB -f:en-ca                # Alberta
php $SCRIPT_PATH/$SCRIPT BC -f:en-ca                # British Columbia
php $SCRIPT_PATH/$SCRIPT MB -f:en-ca                # Manitoba
php $SCRIPT_PATH/$SCRIPT NB -f:en-ca                # New Brunswick
php $SCRIPT_PATH/$SCRIPT NL -f:en-ca                # Newfoundland and Labrador
php $SCRIPT_PATH/$SCRIPT NS -f:en-ca                # Nova Scotia
php $SCRIPT_PATH/$SCRIPT NT -f:en-ca                # Northwest Territories
php $SCRIPT_PATH/$SCRIPT NU -f:en-ca                # Nunavut
php $SCRIPT_PATH/$SCRIPT ON -f:en-ca                # Ontario
php $SCRIPT_PATH/$SCRIPT PE -f:en-ca                # Prince Edward Island
php $SCRIPT_PATH/$SCRIPT QC -f:en-ca                # Quebec
php $SCRIPT_PATH/$SCRIPT SK -f:en-ca                # Saskatchewan
php $SCRIPT_PATH/$SCRIPT YT -f:en-ca                # Yukon

# United Kingdom countries
# (administrative regions were too complex to use
# - cf. http://www.geonames.org/GB/administrative-division-united-kingdom.html)
# (could go by their "region names" or counties, but that is the full name
# - still complex to figure out what that should be) 
php $SCRIPT_PATH/$SCRIPT England -f:en-gb           # England
php $SCRIPT_PATH/$SCRIPT Scotland -f:en-gb          # Scotland
php $SCRIPT_PATH/$SCRIPT Craigavon -f:en-gb         # Near center of Northern Ireland

# Major cities of Ireland
php $SCRIPT_PATH/$SCRIPT Galway -f:en-ie
php $SCRIPT_PATH/$SCRIPT Dublin -f:en-ie
php $SCRIPT_PATH/$SCRIPT Limerick -f:en-ie
php $SCRIPT_PATH/$SCRIPT Cork -f:en-ie

# Australian provinces (http://www.citypopulation.de/Australia-UC.html)

php $SCRIPT_PATH/$SCRIPT ACT -f:en-au               # Austrialian Capital Territory
php $SCRIPT_PATH/$SCRIPT CHR -f:en-ca               # Christmas Island
php $SCRIPT_PATH/$SCRIPT COC -f:en-ca               # Cocos Islands
php $SCRIPT_PATH/$SCRIPT JB -f:en-ca                # Jervis Bay
php $SCRIPT_PATH/$SCRIPT NSW -f:en-ca               # New South Wales
php $SCRIPT_PATH/$SCRIPT NT -f:en-ca                # Northern Territory
php $SCRIPT_PATH/$SCRIPT QLD -f:en-ca               # Queensland
php $SCRIPT_PATH/$SCRIPT SA -f:en-ca                # South Australia
php $SCRIPT_PATH/$SCRIPT TAS -f:en-ca               # Tasmania
php $SCRIPT_PATH/$SCRIPT VIC -f:en-ca               # Victoria
php $SCRIPT_PATH/$SCRIPT WA -f:en-ca                # Western Australia

# Non-English-speaking countries
# These are not working with the country name or ISO code, so commented out for now.
# Also, listings were not in English.

# php $SCRIPT_PATH/$SCRIPT Argentina -f:en-ar         # Argentina              
# php $SCRIPT_PATH/$SCRIPT Austria -f:en-at           # Austria                    
# php $SCRIPT_PATH/$SCRIPT Belgium -f:en-be           # Belgium                  
# php $SCRIPT_PATH/$SCRIPT Brazil -f:en-br            # Brazil
# php $SCRIPT_PATH/$SCRIPT China -f:en-cn             # China
# php $SCRIPT_PATH/$SCRIPT France -f:en-fr            # France
# php $SCRIPT_PATH/$SCRIPT Germany -f:en-de           # Germany
# php $SCRIPT_PATH/$SCRIPT India -f:en-in             # India
# php $SCRIPT_PATH/$SCRIPT Italy -f:en-it             # Italy
# php $SCRIPT_PATH/$SCRIPT Japan -f:en-jp             # Japan
# php $SCRIPT_PATH/$SCRIPT Korea -f:en-kr             # Korea
# php $SCRIPT_PATH/$SCRIPT Mexico -f:en-mx            # Mexico
# php $SCRIPT_PATH/$SCRIPT Netherlands -f:en-nl       # Netherlands
# php $SCRIPT_PATH/$SCRIPT Portugal -f:en-pt          # Portugal
# php $SCRIPT_PATH/$SCRIPT Russia -f:en-ru            # Russia
# php $SCRIPT_PATH/$SCRIPT South Africa -f:en-za      # South Africa
# php $SCRIPT_PATH/$SCRIPT Spain -f:en-es             # Spain
# php $SCRIPT_PATH/$SCRIPT Sweden -f:en-se            # Sweden
# php $SCRIPT_PATH/$SCRIPT Switzerland -f:en-ch       # Switzerland
